### Test Dummy Search Query
POST http://localhost:8080/api/v1/matcher
Content-Type: application/json

{
  "phoneNumber": "0600000001",
  "messageText": "Looking for internship as hbo student! I study graphic design."
}

