### Test Dummy Search Query (Success)
POST http://localhost:8080/api/v1/matcher
Content-Type: application/json

{
  "phoneNumber": "0600000001",
  "messageText": "Creative internship, 10 weeks, 400 hours, with guidance, learn creative business industry, Amsterdam, start 13 April 2025"
}


### Test Dummy Search Query (No Student Found)
POST http://localhost:8080/api/v1/matcher
Content-Type: application/json

{
  "phoneNumber": "0600000000",
  "messageText": "Looking for internship as software dev student!"
}