
### Test Dummy Search Query
POST http://localhost:8080/api/v1/matcher
Content-Type: application/json

{
  "name": "{{my.name}}",
  "phoneNumber": "{{my.number}}",
  "messageText": "Looking for internship as hbo student! I study graphic design."
}
